---

- hosts: all
  become: true
  pre_tasks:

  - name:  install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (Debian)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Debian"

- hosts: web_servers
  become: true
  tasks:


  - name: install apache2 and php packages for Debian
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"


  - name: add apache and php support for apache on CentOS
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb (Debian)
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Debian"


- hosts: file_servers
  become: true
  tasks:

  - name: install samba package on all file servers
    package:
      name: samba
      state: latest

